name: autoterm_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scipy
  - math
  - subprocess
  - os
  - shutil
  - datetime
  - cv2
  - PIL
  - matplotlib-base
  - pyfftw
  - ttictoc
  - json
  - multiprocessing
  - fiona
  - geopandas
  - shapely
  - rasterio
