name: autoterm_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scipy
  - opencv
  - matplotlib-base
  - pyfftw
  - fiona
  - geopandas
  - shapely
  - rasterio
